version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    exclude:
      - templates/**
    overwrite: true
  
  # Environment configuration
  - source: templates/processed/.env
    destination: /var/www/html/
    overwrite: true
  
  # Logstash configuration
  - source: templates/processed/syslog-tcp-forward.conf
    destination: /etc/logstash/conf.d/
    overwrite: true
  
  # Filebeat configuration 
  - source: templates/processed/filebeat.yml
    destination: /etc/filebeat/
    overwrite: true
    
  - source: templates/processed/config.yaml
    destination: /etc/otelcol-contrib/
    overwrite: true 

file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
